export const courses = [
  { id:'abacus', title:'Abacus & Mental Maths', category:'core', age:'4–14 years', badge:'THE XTRAGENIUS FOUNDATION', image:'/images/classroom.jpg', alt:'Young learners practising together in a classroom', description:'Small beads. Big discoveries. A stronger foundation for every kind of learning.', skills:['Concentration','Speed','Memory','Visualization'], provider:'Xtragenius programme', curriculum:['Discover the abacus: place value, number sense and hands-on exploration.','Build accuracy through guided addition and subtraction practice.','Move from physical beads to mental pictures with visualization exercises.','Develop fluent mental calculation with progressive challenges.'], credential:'Learn with the Xtragenius educator network. Your assigned instructor’s profile and credentials will be shared before enrolment.' },
  { id:'vedic', title:'Vedic Mathematics', category:'core', age:'8–14 years', badge:'THE XTRAGENIUS FOUNDATION', image:'/images/mathematics.jpg', alt:'Mathematical patterns and equations on a chalkboard', description:'Discover the patterns in numbers. Turn “I can’t” into “I’ve got this.”', skills:['Speed','Concentration','Memory'], provider:'Xtragenius programme', curriculum:['Explore number patterns and flexible ways to calculate.','Practise efficient strategies for addition and subtraction.','Build multiplication skills through visual and mental techniques.','Apply strategies to age-appropriate mathematical challenges.'], credential:'Guided by the Xtragenius educator network, with instructor qualifications confirmed during programme counselling.' },
  { id:'handwriting', title:'The Art of Handwriting', category:'creative', age:'5–14 years', badge:'THE XTRAGENIUS FOUNDATION', image:'/images/handwriting.jpg', alt:'A learner practising careful handwriting in a notebook', description:'More than beautiful letters. Focus, expression and confidence on every page.', skills:['Concentration','Visualization'], provider:'Xtragenius programme', curriculum:['Establish comfortable posture, pencil grip and writing habits.','Explore letter shapes, spacing and consistent proportions.','Strengthen visual coordination with purposeful writing exercises.','Build writing fluency and personal expression.'], credential:'An Xtragenius programme with educator details shared before enrolment.' },
  { id:'chess', title:'Chess & Strategic Thinking', category:'core', age:'6–14 years', badge:'EXPANDING POSSIBILITIES', art:'chess', symbol:'♞', description:'Think a move ahead. Learn to pause, plan and see a different possibility.', skills:['Concentration','Memory','Visualization'], provider:'Partner programme · Coming soon', curriculum:['Meet the board, the pieces and the rules of play.','Recognise patterns and explore the value of planning.','Practise age-appropriate tactics and positional thinking.','Reflect on decisions through guided games.'], credential:'Partner educators are being onboarded. Instructor profiles and final curriculum will be published when enrolment opens.' },
  { id:'robotics', title:'Robotics & AI for Kids', category:'future', age:'8–14 years', badge:'WHAT’S NEXT IN LEARNING', art:'robotics', symbol:'⌘', description:'From “what if?” to “look what I made.” Bring big ideas into the real world.', skills:['Visualization','Concentration'], provider:'Partner programme · Coming soon', curriculum:['Explore how everyday technology works.','Build logical thinking through step-by-step challenges.','Discover robotics and introductory AI concepts.','Create, test and improve a guided project.'], credential:'Partner educators are being onboarded. Specific equipment, educator credentials and programme format will be confirmed before launch.' },
  { id:'entrepreneur', title:'Young Creators & Entrepreneurs', category:'future', age:'9–14 years', badge:'WHAT’S NEXT IN LEARNING', art:'entrepreneur', symbol:'↗', description:'Ideas deserve a beginning. Build creative thinking, communication and initiative.', skills:['Visualization','Memory','Concentration'], provider:'Partner programme · Coming soon', curriculum:['Notice everyday problems and imagine useful ideas.','Explore creative communication and digital storytelling.','Develop a simple project from an idea to a prototype.','Share a pitch and learn from constructive feedback.'], credential:'Partner educators are being onboarded. Instructor credentials and the complete programme will be shared before enrolment.' }
];

export const skillDetails = [
  ['Concentration','A little more focus. A whole world of discovery.','Concentration gives children the space to engage deeply with a task. Through intentional practice, structured challenges and hands-on learning, we help them build the habit of staying curious and staying with it.'],
  ['Speed','Clear thinking. Growing fluency.','Speed grows from familiarity and understanding. Guided practice in mental mathematics helps children respond with greater confidence while keeping accuracy at the centre of learning.'],
  ['Memory','New ideas, connected to what they already know.','Memory is more than repetition. Patterns, mental imagery and meaningful connections help children develop recall and put their learning to use in different situations.'],
  ['Visualization','First, imagine it. Then, make it possible.','Visualization helps children hold and explore ideas in their minds. From imagining an abacus to planning a chess move, mental imagery opens up another way to understand and solve a challenge.']
];

export const testimonials = [
  { quote:'My daughter struggled to sit still for ten minutes. Six months into Abacus & Mental Maths, she asks to practise before I ask her.', name:'Priya Ramesh', role:'Parent, Abacus & Mental Maths · Chennai', initials:'PR', bg:'#dba34b' },
  { quote:'What stood out wasn’t the speed — it was how patiently the instructors built his confidence first. The numbers followed.', name:'Arvind Mehta', role:'Parent, Vedic Mathematics · Coimbatore', initials:'AM', bg:'#718098' },
  { quote:'As a partner academy, the onboarding support and structured curriculum made it simple to bring Xtragenius into our centre.', name:'Lakshmi Narayanan', role:'Academy Partner · Madurai', initials:'LN', bg:'#536757' },
  { quote:'He used to say maths was boring. Now he counts down the days to his Xtragenius class every week.', name:'Sundar Krishnan', role:'Parent, Abacus & Mental Maths · Madurai', initials:'SK', bg:'#a68346' },
];

export const banners = [
  { eyebrow:'A BIGGER STAGE FOR EXTRAORDINARY MINDS', title:'Small beads.<br>A world of possibility.', description:'Xtragenius Global Abacus & Mental Maths Competition', action:'Explore the competition', topic:'competition', symbol:'♜' },
  { eyebrow:'BUILT ON EXPERIENCE. OPEN TO POSSIBILITY.', title:'Your expertise.<br>A nationwide impact.', description:'Join our network of academies, teachers and institutes.', action:'Become a partner', topic:'partnership', symbol:'✳' },
  { eyebrow:'NEW SKILLS. NEW WAYS TO SEE THE WORLD.', title:'Their next big idea<br>starts with a little curiosity.', description:'Robotics · Chess · AI for Kids · Creative Digital Skills · Young Entrepreneurs', action:'Explore new programmes', href:'#programmes', symbol:'↗' },
  { eyebrow:'THE NEXT CHAPTER OF XTRAGENIUS', title:'An established legacy.<br>Now, a new way to learn.', description:'Discover our online learning plans, upcoming programmes and partner opportunities.', action:'Discover what’s next', topic:'latest announcements', symbol:'◎' }
];

export const galleryItems = [
  { id:1, category:'Classroom', title:'A focused abacus session', bg:'#e1e4d9', fg:'#334f61', symbol:'◎' },
  { id:2, category:'Competitions', title:'State-level mental maths meet', bg:'#e9dfcd', fg:'#a68346', symbol:'✳' },
  { id:3, category:'Centres', title:'Our Chennai learning centre', bg:'#dce5e2', fg:'#334f61', symbol:'⌘' },
  { id:4, category:'Educators', title:'Training our instructor network', bg:'#dedbcc', fg:'#536757', symbol:'♞' },
  { id:5, category:'Classroom', title:'Small group, focused learning', bg:'#f4ead6', fg:'#a08b60', symbol:'+' },
  { id:6, category:'Events', title:'Annual achievers’ celebration', bg:'#e1e4d9', fg:'#334f61', symbol:'↗' },
  { id:7, category:'Competitions', title:'Regional abacus championship', bg:'#dce5e2', fg:'#334f61', symbol:'♜' },
  { id:8, category:'Centres', title:'A partner academy, in session', bg:'#e9dfcd', fg:'#a68346', symbol:'◎' },
  { id:9, category:'Classroom', title:'Handwriting practice, up close', bg:'#dedbcc', fg:'#536757', symbol:'✳' },
];

